import { SurfaceProfile } from './types';

export const presetSurfaces: Record<string, SurfaceProfile> = {
  mobilePortrait: {
    id: 'mobilePortrait',
    name: 'Mobile Portrait Interstitial',
    description: 'Standard 9:16 vertical smartphone screen with safe area padding and touch target constraints.',
    width: 320,
    height: 480,
    safeArea: { top: 24, right: 16, bottom: 24, left: 16 },
    minTapTarget: 44,
    minTextSize: 14,
    viewingDistance: 'near',
    touchOnly: true,
    theme: 'dark',
  },
  mobileLandscape: {
    id: 'mobileLandscape',
    name: 'Mobile Landscape Banner',
    description: 'Horizontal smartphone orientation focusing on side-by-side hero image and action CTA.',
    width: 640,
    height: 360,
    safeArea: { top: 16, right: 24, bottom: 16, left: 24 },
    minTapTarget: 44,
    minTextSize: 13,
    viewingDistance: 'near',
    touchOnly: true,
    theme: 'dark',
  },
  broadcastLowerThird: {
    id: 'broadcastLowerThird',
    name: 'Broadcast Lower-Third',
    description: 'Ultra-wide TV ticker stream with mandatory large text for far viewing distances.',
    width: 1920,
    height: 250,
    safeArea: { top: 20, right: 60, bottom: 20, left: 60 },
    minTapTarget: 0,
    minTextSize: 32,
    viewingDistance: 'far',
    touchOnly: false,
    theme: 'vibrant',
  },
  squareKiosk: {
    id: 'squareKiosk',
    name: 'Retail Kiosk Screen',
    description: 'High-res square touchscreen requiring extra-large touch targets for accessibility.',
    width: 1080,
    height: 1080,
    safeArea: { top: 40, right: 40, bottom: 40, left: 40 },
    minTapTarget: 60,
    minTextSize: 22,
    viewingDistance: 'medium',
    touchOnly: true,
    theme: 'light',
  },
  microBanner: {
    id: 'microBanner',
    name: 'Micro Ad Banner',
    description: 'Severely space-constrained 300x100 unit designed to test priority-based element degradation & dropping.',
    width: 300,
    height: 100,
    safeArea: { top: 8, right: 8, bottom: 8, left: 8 },
    minTapTarget: 36,
    minTextSize: 11,
    viewingDistance: 'near',
    touchOnly: true,
    theme: 'dark',
  },
};
